[env:m5stack-atom]
platform = espressif32@^6.8.0
board = m5stack-atom
framework = arduino
monitor_speed = 115200

; micro-ROS 設定
board_microros_distro = jazzy
board_microros_transport = wifi

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    adafruit/Adafruit_VL53L0X@^1.2.4
    fastled/FastLED@^3.7.0
